add-docker
OrlovDeniss/java-shareit pull request #7
Opened 2023-06-28 06:17 UTC by OrlovDeniss

2023-06-28 16:26 UTC, andrew-larkin requested changes
Привет! Очень сильная работа, много удачных решений и доп.инструментов используется, отлично. Тесты написаны хорошо, докер запускается без проблем. Остается пару корректировок внести и приложение будет полностью готово.

2023-06-28 16:26 UTC, andrew-larkin commented on docker-compose.yml
> +  gateway:
сюда тоже стоит добавить настройку restart on failure

2023-06-28 16:26 UTC, andrew-larkin commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
закомментированный код удаляем везде

2023-06-29 07:17 UTC, OrlovDeniss commented
Спасибо за ревью! поправил недочёты)

2023-06-29 16:16 UTC, merged